version: '2.6.1'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ITForum
    ports:
      - 8000:8000
    depends_on:
      - redis


  celery:
    build: .
    command: celery -A main worker -l info
    volumes:
      - .:/usr/src/main
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    command: celery -A main beat -l info
    volumes:
      - .:/usr/src/main
    depends_on:
      - django
      - redis


  redis:
    image: redis:alpine
    command: redis-server

  flower:
    image: mher/flower:0.9.7
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - 5557:5555
    depends_on:
      - redis