# Generated by Django 4.1 on 2022-08-27 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без наименование', max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без темы', max_length=200, verbose_name='Тема')),
                ('DateOfCreation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('Description', models.TextField(null=True, verbose_name='Описание')),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forumBase.category', verbose_name='Категория')),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_topics', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
        migrations.CreateModel(
            name='CommentTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentText', models.TextField(verbose_name='Комментарий')),
                ('DateOfComment', models.DateTimeField(auto_now_add=True)),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumBase.topic', verbose_name='Тема')),
                ('User', models.ForeignKey(default='profile delete', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
