# Generated by Django 4.1 on 2022-09-01 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Форум')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='commenttopic',
            options={'ordering': ['DateOfComment']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['DateOfCreation']},
        ),
        migrations.AddField(
            model_name='commenttopic',
            name='CommentDislike',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commenttopic',
            name='CommentFather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forumBase.commenttopic'),
        ),
        migrations.AddField(
            model_name='commenttopic',
            name='CommentLike',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='AveregeRaiting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('Открыта', 1), ('Закрыта', 2), ('Решена', 3)], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='commenttopic',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagees', to='forumBase.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='commenttopic',
            name='User',
            field=models.ForeignKey(default='profile delete', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TopicSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumBase.topic')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicRaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Пойдет'), (2, 'Плохо'), (1, 'Лучше не видеть!')], verbose_name='Оценка обсуждению')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rait', to='forumBase.topic')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raituser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentLike', models.PositiveIntegerField(default=0)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='forumBase.commenttopic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentDislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentDislike', models.PositiveIntegerField(default=0)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_dislikes', to='forumBase.commenttopic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_dislikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='forumBase.forum'),
        ),
    ]
