# Generated by Django 4.1 on 2022-08-31 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Форум')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='commenttopic',
            name='CommentDislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commenttopic',
            name='CommentFather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forumBase.commenttopic'),
        ),
        migrations.AddField(
            model_name='commenttopic',
            name='CommentLike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('Открыта', 1), ('Закрыта', 2), ('Решена', 3)], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='commenttopic',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagees', to='forumBase.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TopicSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumBase.topic')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicRaiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.PositiveSmallIntegerField(choices=[('Nice', 5), ('Good', 4), ('Middling', 3), ('Bad', 2), ('Terrible', 1)])),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forumBase.topic')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='forumBase.forum'),
        ),
    ]
