# Generated by Django 4.1 on 2022-08-31 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumBase', '0002_forum_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenttopic',
            options={'ordering': ['DateOfComment']},
        ),
        migrations.AlterField(
            model_name='commenttopic',
            name='User',
            field=models.ForeignKey(default='profile delete', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
