# Generated by Django 4.1 on 2022-08-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumBase', '0002_commenttopic_commentdislike_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['DateOfCreation']},
        ),
        migrations.AlterField(
            model_name='commenttopic',
            name='CommentFather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forumBase.commenttopic'),
        ),
        migrations.AlterField(
            model_name='commenttopic',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagees', to='forumBase.topic', verbose_name='Тема'),
        ),
    ]
