# Generated by Django 4.1 on 2022-08-31 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forumBase', '0003_alter_commenttopic_options_alter_commenttopic_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['DateOfCreation']},
        ),
        migrations.AddField(
            model_name='topic',
            name='AveregeRaiting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='topicraiting',
            name='Grade',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Nice'), (4, 'Good'), (3, 'Middling'), (2, 'Bad'), (1, 'Terrible')], verbose_name='Оценка обсуждению'),
        ),
        migrations.AlterField(
            model_name='topicsubscribe',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
