# Generated by Django 4.1 on 2022-08-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumBase', '0004_forum_category_forum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('Открыта', 1), ('Закрыта', 2), ('Решена', 3)], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='forumBase.forum'),
        ),
    ]
