# Generated by Django 4.1 on 2022-09-01 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forumBase', '0004_alter_topic_options_topic_averegeraiting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicraiting',
            name='Grade',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Пойдет'), (2, 'Плохо'), (1, 'Лучше не видеть!')], verbose_name='Оценка обсуждению'),
        ),
        migrations.AlterField(
            model_name='topicraiting',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rait', to='forumBase.topic'),
        ),
    ]
