# Generated by Django 4.1 on 2022-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='', upload_to='userImg/'),
            preserve_default=False,
        ),
    ]
